services:
  - type: web
    name: classfind
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: classfind-db
          property: connectionString

databases:
  - name: classfind-db
